# Generated by Django 6.0.5 on 2026-05-11 11:12

import movies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_aboutcompany_faq_news_privacypolicy_promocode_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(null=True, validators=[movies.models.validate_employee_age], verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=20, null=True, validators=[movies.models.validate_phone_number], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=100, verbose_name='Должность'),
        ),
    ]
