# Generated by Django 6.0.5 on 2026-05-18 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_clientprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='paid_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена оплаты'),
        ),
    ]
